const Icons = {
    //sun
    //moon
    //cloud-sun-rain
    //cloud-sun
    //cloud-moon
    //cloud-moon-rain
    manha: {
        ec: "cloud-sun-rain",
        ci: "cloud-sun-rain",
        c: "cloud-sun-rain",
        in: "cloud-sun",
        pp: "cloud-sun-rain",
        cm: "cloud-sun-rain",
        cn: "cloud-sun-rain",
        pt: "Pancadas de Chuva a Tarde",
        pm: "Pancadasde de Chuva pela Manhã",
        np: "cloud-sun-rain",
        pc: "cloud-sun-rain",
        pn: "cloud-sun",
        cv: "cloud-sun-rain",
        ch: "cloud-sun-rain",
        t: "Tempestade",
        ps: "sun",
        e: "cloud-moon",
        n: "cloud-sun",
        cl: "sun",
        nv: "Nevoeiro",
        g: "Geada",
        ne: "Neve",
        nd: "sun",
        pnt: "Pancadas de Chuva a Noite",
        psc: "cloud-sun-rain",
    },
    tarde: {
        ec: "cloud-sun-rain",
        ci: "cloud-sun-rain",
        c: "cloud-sun-rain",
        in: "cloud-sun",
        pp: "cloud-sun-rain",
        cm: "cloud-sun-rain",
        cn: "cloud-sun-rain",
        pt: "Pancadas de Chuva a Tarde",
        pm: "Pancadasde de Chuva pela Manhã",
        np: "cloud-sun-rain",
        pc: "cloud-sun-rain",
        pn: "cloud-sun",
        cv: "cloud-sun-rain",
        ch: "cloud-sun-rain",
        t: "Tempestade",
        ps: "sun",
        e: "cloud-moon",
        n: "cloud-sun",
        cl: "sun",
        nv: "Nevoeiro",
        g: "Geada",
        ne: "Neve",
        nd: "sun",
        pnt: "Pancadas de Chuva a Noite",
        psc: "cloud-sun-rain",
    },
    noite: {
        ec: "cloud-moon-rain",
        ci: "cloud-moon-rain",
        c: "cloud-moon-rain",
        in: "cloud-moon",
        pp: "cloud-moon-rain",
        cm: "cloud-moon-rain",
        cn: "cloud-moon-rain",
        pt: "Pancadas de Chuva a Tarde",
        pm: "Pancadasde de Chuva pela Manhã",
        np: "cloud-moon-rain",
        pc: "cloud-moon-rain",
        pn: "cloud-moon",
        cv: "cloud-moon-rain",
        ch: "cloud-moon-rain",
        t: "Tempestade",
        ps: "moon",
        e: "cloud-moon",
        n: "cloud-moon",
        cl: "moon",
        nv: "Nevoeiro",
        g: "Geada",
        ne: "Neve",
        nd: "moon",
        pnt: "Pancadas de Chuva a Noite",
        psc: "cloud-moon-rain",
    },

}

export default Icons;